image: docker:19
services:
- docker:dind

stages:
- build
- publish

before_script:
- apk add make

build:
  stage: build
  script:
  - make docker-build
  except:
  - main

publish:
  stage: publish
  script:
  - make docker-build
  - make docker-push
  only:
  - main
